---

# Testing playbook.... use with VM


- hosts: localhost
  vars:
    centreon_url: "http://192.168.189.128/centreon"
    centreon_api_user: "admin"
    centreon_api_pass: "centreon"
  handlers:
    - name: "centreon api applycfg"
      centreon_poller:
        url: "{{ centreon_url }}"
        username: "{{ centreon_api_user }}"
        password: "{{ centreon_api_pass }}"
      listen: "centreon api applycfg"
  tasks:
    - name: Add host to Centreon
      centreon_host:
        url: "{{ centreon_url }}"
        username: "{{ centreon_api_user }}"
        password: "{{ centreon_api_pass }}"
        name: "ansible-test"
        alias: "Alias_ansible"
        ipaddr: "127.0.0.2"
        hosttemplates:
          - OS-Linux-SNMP-custom
          - App-DB-MySQL
        hostgroups:
          - Linux-Servers
          - hg1
        instance: Central
        status: enabled
        state: present
        params:
          action_url: http://example.org/test
          notes: "My Server"
        applycfg: False
      delegate_to: localhost
      notify: "centreon api applycfg"



