---

# Testing playbook.... use with VM


- hosts: localhost
  vars:
    centreon_url: "http://192.168.189.128/centreon"
    centreon_api_user: "admin"
    centreon_api_pass: "centreon"

  handlers:
    - name: "centreon api applycfg"
      centreon_poller:
        url: "{{ centreon_url }}"
        username: "{{ centreon_api_user }}"
        password: "{{ centreon_api_pass }}"
      listen: "centreon api applycfg"
      delegate_to: localhost

  tasks:
    - name: Add host to Centreon
      centreon_host:
        url: "{{ centreon_url }}"
        username: "{{ centreon_api_user }}"
        password: "{{ centreon_api_pass }}"
        name: "ansible-test"
        alias: "Alias_ansible"
        ipaddr: "127.0.0.12"
        hosttemplates:
          - OS-Linux-SNMP-custom
          - App-DB-MySQL
        hostgroups:
          - Linux-Servers
          - hg2
        hostgroups_action: set
        instance: Central
        status: enabled
        state: present
        #params:
        #  action_url: http://example.org/test
        #  notes: "My Server"
        macros:
          - name: TEST
            value: VALUE2
        applycfg: False
      delegate_to: localhost
      notify: "centreon api applycfg"
  tags:
    - host


- hosts: localhost
  vars:
    centreon_url: "http://192.168.189.128/centreon"
    centreon_api_user: "admin"
    centreon_api_pass: "centreon"
  tasks:
    - name: Hostgroup
      centreon_hostgroup:
        url: "{{ centreon_url }}"
        username: "{{ centreon_api_user }}"
        password: "{{ centreon_api_pass }}"
        hg:
          - name: test
            alias: test
          - name: test2r
            alias: test2r
          - name: test4
        state: present
      delegate_to: localhost
  tags:
    - hostgroup


- hosts: localhost
  vars:
    centreon_url: "http://192.168.189.128/centreon"
    centreon_api_user: "admin"
    centreon_api_pass: "centreon"

  tasks:
    - name: Add host to Centreon
      centreon_host:
        url: "{{ centreon_url }}"
        username: "{{ centreon_api_user }}"
        password: "{{ centreon_api_pass }}"
        name: "ansible-test"
        hosttemplates:
          - OS-Linux-SNMP-custom
          - App-DB-MySQL
      delegate_to: localhost
      notify: "centreon api applycfg"
  tags:
    - test


